@echo off
set localdir=%cd%
echo Making reference...
cd ../../tools/make_reference/reference
copy %localdir%\test.s ..\test.s
echo ZDS assembler...
make rebuildall -f ../reference.mak
echo HEX conversion...
..\..\..\tools\hex2bin reference.hex
echo Copying reference.bin...
copy reference.bin %localdir%\reference.bin
cd %localdir%