@echo off
set localdir=%cd%
echo Making reference...
cd ../../tools/make_reference/reference
REM Special copy of reftest, not test itself, due to ZDS syntax, same binary
copy %localdir%\reftest.s ..\test.s
echo ZDS assembler...
"C:\ZiLOG\ZDSII_eZ80Acclaim!_5.3.5\bin\make.exe" rebuildall -f ../reference.mak
echo HEX conversion...
..\..\..\tools\hex2bin reference.hex
echo Copying reference.bin...
copy reference.bin %localdir%\reference.bin
cd %localdir%